In a 1965 article in Public Opinion Quarterly, psychologist Stanley Milgram reported on a study where he intentionally lost letters to see if the nature of the address on the letter would affect return rates when people found the letters lying on a public sidewalk. For example, he found that letters addressed to a subversive organization such as Friends of the Nazi Party were far less likely to be returned than those addressed to an individual or to a medical research organization.
In 1999 Grinnell College students Laurelin Muir and Adam Gratch conducted an experiment similar to Milgram's for an introductory statistics class. They intentionally
"lost 140 letters" in either the city of Des Moines, the town of Grinnell, or on the Grinnell College campus. Half of each sample were addressed to Friends of the Confederacy and the other half to lowa Peaceworks. Do the return rates differ depending on address? Get the data in LostLetter. Use logistic regression and analyze the data to decide, location by location, if there is a difference. Summarize your findings.

In [7]:
# Install the package if you haven't already
install.packages("Stat2Data")

# Load the library and the dataset
library(Stat2Data)
data("LostLetter")

# View the first few rows
head(LostLetter)

The downloaded binary packages are in
	/var/folders/rk/hm976cm116b00fkw44hrlkgc0000gn/T//Rtmp4SU2g6/downloaded_packages

  Location  Address    Returned DesMoines GrinnellTown GrinellCampus Peaceworks
1 DesMoines Peaceworks 1        1         0            0             1
2 DesMoines Peaceworks 1        1         0            0             1
3 DesMoines Peaceworks 1        1         0            0             1
4 DesMoines Peaceworks 1        1         0            0             1
5 DesMoines Peaceworks 1        1         0            0             1
6 DesMoines Peaceworks 1        1         0            0             1
  Confederacy
1 0
2 0
3 0
4 0
5 0
6 0

In [8]:
# Import libraries
library(dplyr)
library(ggplot2)
library(repr)
library(stats)
# Set the parameters for the plot sizes for all plots below
options(repr.plot.width=6, repr.plot.height=6)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [9]:
data(LostLetter)
attach(LostLetter)
head(LostLetter)

model1 <- glm(Returned ~ Address + Location, family = "binomial")
summary(model1)

  Location  Address    Returned DesMoines GrinnellTown GrinellCampus Peaceworks
1 DesMoines Peaceworks 1        1         0            0             1
2 DesMoines Peaceworks 1        1         0            0             1
3 DesMoines Peaceworks 1        1         0            0             1
4 DesMoines Peaceworks 1        1         0            0             1
5 DesMoines Peaceworks 1        1         0            0             1
6 DesMoines Peaceworks 1        1         0            0             1
  Confederacy
1 0
2 0
3 0
4 0
5 0
6 0

Call:
glm(formula = Returned ~ Address + Location, family = "binomial")

Coefficients:
                       Estimate Std. Error z value Pr(>|z|)
(Intercept)             -0.4243     0.2995  -1.417 0.156571
AddressPeaceworks        1.4166     0.3983   3.557 0.000376 ***
LocationGrinnellCampus  -1.5089     0.5965  -2.530 0.011417 *
LocationGrinnellTown     1.2520     0.4786   2.616 0.008897 **
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 189.95  on 139  degrees of freedom
Residual deviance: 158.40  on 136  degrees of freedom
AIC: 166.4

Number of Fisher Scoring iterations: 4

In [10]:
# df * 1.2 > residual deviance, therefore try quasibinomial

model2 <- glm(Returned ~ Address + Location, family = "quasibinomial")
summary(model2)

Call:
glm(formula = Returned ~ Address + Location, family = "quasibinomial")

Coefficients:
                       Estimate Std. Error t value Pr(>|t|)
(Intercept)             -0.4243     0.2989  -1.420 0.157979
AddressPeaceworks        1.4166     0.3974   3.564 0.000504 ***
LocationGrinnellCampus  -1.5089     0.5952  -2.535 0.012375 *
LocationGrinnellTown     1.2520     0.4776   2.622 0.009750 **
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for quasibinomial family taken to be 0.9957605)

    Null deviance: 189.95  on 139  degrees of freedom
Residual deviance: 158.40  on 136  degrees of freedom
AIC: NA

Number of Fisher Scoring iterations: 4

what hypothesis can we form here, do people do acts of kindness depending on teh recipeint is it
saturated model = put all variables as dummy variables in the model, not randomization but puts dummy variables
doesn't put numerical variabels makes categories

In [11]:
G <- 158.40 - 157.22 #null.deviance - residual.deviance
df <- 136 - 134 #null.df - residual.df
p <- pchisq(G, df, lower.tail=F)
cat("G =", G, "DF =", df, "P-value =", p)

G = 1.18 DF = 2 P-value = 0.5543273

In [12]:
table(Location[Returned ==1], Address[Returned == 1]) /
table(Location, Address)

                 Confederacy Peaceworks
  DesMoines            0.425      0.700
  GrinnellCampus       0.100      0.400
  GrinnellTown         0.650      0.950

In [14]:
model3 <- glm(Returned ~ GrinellCampus + GrinnellTown + Peaceworks +
I(GrinellCampus*Peaceworks) +
I(GrinnellTown*Peaceworks)
, family = "binomial")
summary(model3)
model3 <- glm(Returned ~ Location * Address
, family = "binomial")
summary(model3)

Call:
glm(formula = Returned ~ GrinellCampus + GrinnellTown + Peaceworks +
    I(GrinellCampus * Peaceworks) + I(GrinnellTown * Peaceworks),
    family = "binomial")

Coefficients:
                              Estimate Std. Error z value Pr(>|z|)
(Intercept)                    -0.3023     0.3198  -0.945   0.3446
GrinellCampus                  -1.8949     1.1016  -1.720   0.0854 .
GrinnellTown                    0.9213     0.5675   1.623   0.1045
Peaceworks                      1.1496     0.4705   2.443   0.0145 *
I(GrinellCampus * Peaceworks)   0.6422     1.3225   0.486   0.6273
I(GrinnellTown * Peaceworks)    1.1758     1.2222   0.962   0.3360
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 189.95  on 139  degrees of freedom
Residual deviance: 157.22  on 134  degrees of freedom
AIC: 169.22

Number of Fisher Scoring iterations: 5

Call:
glm(formula = Returned ~ Location * Address, family = "binomial")

Coefficients:
                                         Estimate Std. Error z value Pr(>|z|)
(Intercept)                               -0.3023     0.3198  -0.945   0.3446
LocationGrinnellCampus                    -1.8949     1.1016  -1.720   0.0854 .
LocationGrinnellTown                       0.9213     0.5675   1.623   0.1045
AddressPeaceworks                          1.1496     0.4705   2.443   0.0145 *
LocationGrinnellCampus:AddressPeaceworks   0.6422     1.3225   0.486   0.6273
LocationGrinnellTown:AddressPeaceworks     1.1758     1.2222   0.962   0.3360
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 189.95  on 139  degrees of freedom
Residual deviance: 157.22  on 134  degrees of freedom
AIC: 169.22

Number of Fisher Scoring iterations: 5

with the given set how can we increase hte number of variables9
as many variables as we can think of put in the model with the amount of data that we have
cant put more variables or will lose degrees of freedom 
saturation in a linear system as many variables as

In [16]:
# residual deviance (4 parameter model vs saturated)
G <- 158.40 - 157.22 #null.deviance - residual.deviance
df <- 136 - 134 #null.df - residual.df
p <- pchisq(G, df, lower.tail=F)
cat("G =", G, "DF =", df, "P-value =", p)

G = 1.18 DF = 2 P-value = 0.5543273

In [17]:
# empirical proportions
table(Location[Returned ==1], Address[Returned == 1]) /
table(Location, Address)

                 Confederacy Peaceworks
  DesMoines            0.425      0.700
  GrinnellCampus       0.100      0.400
  GrinnellTown         0.650      0.950

In [18]:
m2fit <- unique(model2$fitted)

m2fit <- c(m2fit[2], m2fit[6], m2fit[4], 
           m2fit[1], m2fit[5], m2fit[3])

m3fit <- unique(model3$fitted)

m3fit <- c(m3fit[2], m3fit[6], m3fit[4], 
           m3fit[1], m3fit[5], m3fit[3])


matrix(
  m2fit,
  ncol = 2,
  dimnames = list(
    c("DesMoins", "GrinnellCampus", "GrinnellTown"),
    c("Confederacy", "Peaceworks")
  )
)

matrix(
  m3fit,
  ncol = 2,
  dimnames = list(
    c("DesMoins", "GrinnellCampus", "GrinnellTown"),
    c("Confederacy", "Peaceworks")
  )
)

               Confederacy Peaceworks
DesMoins       0.3954770   0.7295230
GrinnellCampus 0.1263863   0.3736137
GrinnellTown   0.6958529   0.9041471

               Confederacy Peaceworks
DesMoins       0.425       0.70
GrinnellCampus 0.100       0.40
GrinnellTown   0.650       0.95

In [19]:
model1 <- glm(Returned ~ Address + Location, family = "quasibinomial")
summary(model1)

Call:
glm(formula = Returned ~ Address + Location, family = "quasibinomial")

Coefficients:
                       Estimate Std. Error t value Pr(>|t|)
(Intercept)             -0.4243     0.2989  -1.420 0.157979
AddressPeaceworks        1.4166     0.3974   3.564 0.000504 ***
LocationGrinnellCampus  -1.5089     0.5952  -2.535 0.012375 *
LocationGrinnellTown     1.2520     0.4776   2.622 0.009750 **
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for quasibinomial family taken to be 0.9957605)

    Null deviance: 189.95  on 139  degrees of freedom
Residual deviance: 158.40  on 136  degrees of freedom
AIC: NA

Number of Fisher Scoring iterations: 4

Dispersion value/phi super close to 1 - not worth changing the model
Interpret coeffecients of model we design on