### Repeating R intro

In [6]:
x <- c(1, 3, 4, 6, 5, 6)
x

[1] 1 3 4 6 5 6

In [8]:
mean(x)

[1] 4.166667

In [9]:
sd(x)

[1] 1.94079

In [13]:
y <- matrix(x, nrow=3)
y

     [,1] [,2]
[1,] 1    6
[2,] 3    5
[3,] 4    6

In [14]:
apply(y,1,sum)
apply(y,2,sum)

[1]  7  8 10

[1]  8 17

In [20]:
z <- matrix(x, nrow=3, byrow=TRUE)

In [17]:
z

     [,1] [,2]
[1,] 1    3
[2,] 4    6
[3,] 5    6

In [22]:
name <- c("Emily", "Tim", "Jeff")
my.mat <- cbind(name, z)
is.matrix(my.mat)
is.data.frame(my.mat)
my.mat
my.mat[,2]

[1] TRUE

[1] FALSE

     name
[1,] Emily 1 3
[2,] Tim   4 6
[3,] Jeff  5 6

[1] "1" "4" "5"

In [23]:
my.data <- data.frame(name, z)
is.data.frame(my.data)
mean(my.data[,2])

[1] TRUE

[1] 3.333333

In [24]:
names(my.data) <- c("Name","Teeth", "Crawl")
my.data
mean(my.data$Teeth)

  Name  Teeth Crawl
1 Emily 1     3
2 Tim   4     6
3 Jeff  5     6

[1] 3.333333

In [2]:
search()

 [1] ".GlobalEnv"        "jupyter:irkernel"  "package:stats"
 [4] "package:graphics"  "package:grDevices" "package:utils"
 [7] "package:datasets"  "package:methods"   "Autoloads"
[10] "package:base"

In [2]:
MetroHealth83.df <- read.csv(file="/Users/emilyahmad/Downloads/ExamplesDataCSV/MetroHealth83.csv", header=TRUE, sep=",")

In [3]:
names(MetroHealth83.df)

 [1] "City"              "NumMDs"            "RateMDs"
 [4] "NumHospitals"      "NumBeds"           "RateBeds"
 [7] "NumMedicare"       "PctChangeMedicare" "MedicareRate"
[10] "SSBNum"            "SSBRate"           "SSBChange"
[13] "NumRetired"        "SSINum"            "SSIRate"
[16] "SqrtMDs"